[versions]
versions = "0.52.0"
nexus-publish = "2.0.0"

[plugins]
versions = { id = "com.github.ben-manes.versions", version.ref = "versions" }
nexus-publish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexus-publish" }
